### ISSUE TITLE
更新后闪退

### ISSUE THREAD

**Issue by abocd** [v7lin/fake_weibo#31]
环境  flutter  2.0.6  安卓，之前是可以的，后面更新了一下就报错了

报错代码如下，请问是什么原因呢？

`E/AndroidRuntime( 3735): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
E/AndroidRuntime( 3735): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/AndroidRuntime( 3735): 	at java.lang.System.loadLibrary(System.java:1667)
E/AndroidRuntime( 3735): 	at com.weibo.ssosdk.WeiboSsoSdk.<clinit>(SourceFile:23)
E/AndroidRuntime( 3735): 	at com.weibo.ssosdk.WeiboSsoSdk.initConfig(Unknown Source:0)
E/AndroidRuntime( 3735): 	at com.sina.weibo.sdk.a.a.a(SourceFile:29)
E/AndroidRuntime( 3735): 	at com.sina.weibo.sdk.a.a(SourceFile:1043)
E/AndroidRuntime( 3735): 	at com.sina.weibo.sdk.openapi.a.registerApp(SourceFile:38)
E/AndroidRuntime( 3735): 	at io.github.v7lin.weibo_kit.WeiboKitPlugin.onMethodCall(WeiboKitPlugin.java:184)
E/AndroidRuntime( 3735): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime( 3735): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/AndroidRuntime( 3735): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/AndroidRuntime( 3735): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 3735): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/AndroidRuntime( 3735): 	at android.os.Looper.loop(Looper.java:174)
E/AndroidRuntime( 3735): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 3735): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3735): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 3735): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Process ( 3735): Sending signal. PID: 3735 SIG: 9
Lost connection to device.
`

**Comment by v7lin** [comment]
以及升级 SDK 了，由于手上木有相应项目测试，只能麻烦你作测试了，记得将测试结果反馈给我，谢谢！
```yaml
dependencies:
  weibo_kit:
    git:
      url: https://github.com/rxreader/weibo_kit.git
```
