### ISSUE TITLE
执行registerApp报错

### ISSUE THREAD

**Issue by 2534290808** [v7lin/fake_weibo#8]
执行registerApp时会报如下错误
```

W/System.err(30511): java.lang.Exception: visitor login failed
W/System.err(30511): 	at com.weibo.ssosdk.WeiboSsoSdk.getAid(WeiboSsoSdk.java:363)
W/System.err(30511): 	at com.sina.weibo.sdk.sso.WeiboSsoManager.initAid(WeiboSsoManager.java:42)
W/System.err(30511): 	at com.sina.weibo.sdk.sso.WeiboSsoManager.init(WeiboSsoManager.java:37)
W/System.err(30511): 	at com.sina.weibo.sdk.auth.BaseSsoHandler.<init>(BaseSsoHandler.java:53)
W/System.err(30511): 	at com.sina.weibo.sdk.auth.sso.SsoHandler.<init>(SsoHandler.java:17)
W/System.err(30511): 	at io.github.v7lin.fakeweibo.FakeWeiboPlugin.onMethodCall(FakeWeiboPlugin.java:105)
W/System.err(30511): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
W/System.err(30511): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
W/System.err(30511): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
W/System.err(30511): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(30511): 	at android.os.MessageQueue.next(MessageQueue.java:386)
W/System.err(30511): 	at android.os.Looper.loop(Looper.java:175)
W/System.err(30511): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
W/System.err(30511): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(30511): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
W/System.err(30511): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
E/SharesdkPlugin(30511):  Android no need this method, Please use gradle set 
```

**Comment by v7lin** [comment]
微博sdk自身原因，不影响使用
